# -*- coding: utf-8 -*-
"""metplotlib.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U0UgTAMpwLhWheMnu3A7j-Ijv22yZdHm
"""

import seaborn as sns

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

roll_no =[1,4,6,7,3,7,3,8,9,5]
marks =[23,5,6,8,9,2,4,6,7,8]
sample_df = pd.DataFrame({"Rollno": roll_no, "Marks":marks})
sample_df.head()

sns.lineplot(x='Rollno', y= 'Marks', data =sample_df)
plt.title('Student Marks')

