# -*- coding: utf-8 -*-
"""visaul.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U0UgTAMpwLhWheMnu3A7j-Ijv22yZdHm
"""

import seaborn as sns

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

roll_no =[1,4,6,7,3,7,3,8,9,5]
marks =[23,5,6,8,9,2,4,6,7,8]
sample_df = pd.DataFrame({"Rollno": roll_no, "Marks":marks})
sample_df.head()

sns.lineplot(x='Rollno', y= 'Marks', data =sample_df)
plt.title('Student Marks')

seaborn_df= sns.load_dataset('planets')
seaborn_df.head()

# @title orbital_period vs mass

from matplotlib import pyplot as plt
seaborn_df.plot(kind='scatter', x='orbital_period', y='mass', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

df = pd.read_csv('/content/Salary_Data.csv')
df.head()

sns.lineplot(x='Gender', y='Age', data=df)

plt.figure(figsize=(5,3))
sns.lineplot(x='Gender', y='Education Level', data=df, hue='Salary')



